<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "attendance".
 *
 * @property int $id
 * @property int $student_courses_division_id
 * @property int $is_available
 * @property string $date
 * @property int $created_at
 * @property int $updated_at
 *
 * @property StudentCoursesDivision $studentCoursesDivision
 */
class Attendance extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'attendance';
    }
    public function beforeValidate(){
        $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        $this->created_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['student_courses_division_id', 'date'], 'required'],
            [['student_courses_division_id', 'created_at', 'updated_at'], 'integer'],
            [['date'], 'safe'],
            [['is_available'], 'string', 'max' => 1],
            [['student_courses_division_id'], 'exist', 'skipOnError' => true, 'targetClass' => StudentCoursesDivision::className(), 'targetAttribute' => ['student_courses_division_id' => 'id']],
        ];
    }


    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'student_courses_division_id' => Yii::t('app', 'Student Courses Division ID'),
            'is_available' => Yii::t('app', 'Is Available'),
            'date' => Yii::t('app', 'Date'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentCoursesDivision()
    {
        return $this->hasOne(StudentCoursesDivision::className(), ['id' => 'student_courses_division_id']);
    }

    /**
     * @inheritdoc
     * @return AttendanceQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new AttendanceQuery(get_called_class());
    }
}
