<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "chat_group".
 *
 * @property int $id
 * @property string $message
 * @property int $courses_division_id
 * @property int $sender_id
 * @property int $created_at
 * @property int $updated_at
 *
 * @property CoursesDivision $coursesDivision
 * @property User $sender
 */
class ChatGroup extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'chat_group';
    }
    public function beforeValidate()
    { $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        $this->created_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['message', 'courses_division_id', 'sender_id', 'created_at'], 'required'],
            [['message'], 'string'],
            [['courses_division_id', 'sender_id', 'created_at', 'updated_at'], 'integer'],
            [['courses_division_id'], 'exist', 'skipOnError' => true, 'targetClass' => CoursesDivision::className(), 'targetAttribute' => ['courses_division_id' => 'id']],
            [['sender_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['sender_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'message' => Yii::t('app', 'Message'),
            'courses_division_id' => Yii::t('app', 'Courses Division ID'),
            'sender_id' => Yii::t('app', 'Sender ID'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCoursesDivision()
    {
        return $this->hasOne(CoursesDivision::className(), ['id' => 'courses_division_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSender()
    {
        return $this->hasOne(User::className(), ['id' => 'sender_id']);
    }

    /**
     * @inheritdoc
     * @return ChatGroupQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ChatGroupQuery(get_called_class());
    }
}
