<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "club_student".
 *
 * @property int $id
 * @property int $club_id
 * @property int $student_id
 * @property int $is_active
 * @property int $created_at
 * @property int $updated_at
 *
 * @property ChatClub[] $chatClubs
 * @property Club $club
 * @property User $student
 */
class ClubStudent extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'club_student';
    }

    public function beforeValidate(){
        $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        $this->created_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['club_id', 'student_id', 'is_active', 'created_at'], 'required'],
            [['club_id', 'student_id', 'is_active', 'created_at', 'updated_at'], 'integer'],
            [['club_id'], 'exist', 'skipOnError' => true, 'targetClass' => Club::className(), 'targetAttribute' => ['club_id' => 'id']],
            [['student_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['student_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'club_id' => Yii::t('app', 'Club ID'),
            'student_id' => Yii::t('app', 'Student ID'),
            'is_active' => Yii::t('app', 'Is Active'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChatClubs()
    {
        return $this->hasMany(ChatClub::className(), ['club_student_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getClub()
    {
        return $this->hasOne(Club::className(), ['id' => 'club_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudent()
    {
        return $this->hasOne(User::className(), ['id' => 'student_id']);
    }

    /**
     * @inheritdoc
     * @return ClubStudentQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ClubStudentQuery(get_called_class());
    }
}
