<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "courses_division".
 *
 * @property int $id
 * @property int $teacher_id
 * @property int $courses_id
 * @property int $division_id
 * @property string $year
 * @property string $season
 * @property int $created_at
 * @property int $updated_at
 *
 * @property ChatGroup[] $chatGroups
 * @property Courses $courses
 * @property Division $division
 * @property User $teacher
 * @property HomeWork[] $homeWorks
 * @property Quiz[] $quizzes
 * @property StudentCoursesDivision[] $studentCoursesDivisions
 */
class CoursesDivision extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'courses_division';
    }
    public function beforeValidate()
    { $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        $this->created_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['teacher_id', 'courses_id', 'division_id', 'year', 'created_at'], 'required'],
            [['teacher_id', 'courses_id', 'division_id', 'created_at', 'updated_at'], 'integer'],
            [['year'], 'safe'],
            [['season'], 'string'],
            [['courses_id'], 'exist', 'skipOnError' => true, 'targetClass' => Courses::className(), 'targetAttribute' => ['courses_id' => 'id']],
            [['division_id'], 'exist', 'skipOnError' => true, 'targetClass' => Division::className(), 'targetAttribute' => ['division_id' => 'id']],
            [['teacher_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['teacher_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'teacher_id' => Yii::t('app', 'Teacher ID'),
            'courses_id' => Yii::t('app', 'Courses ID'),
            'division_id' => Yii::t('app', 'Division ID'),
            'year' => Yii::t('app', 'Year'),
            'season' => Yii::t('app', 'Season'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getChatGroups()
    {
        return $this->hasMany(ChatGroup::className(), ['courses_division_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCourses()
    {
        return $this->hasOne(Courses::className(), ['id' => 'courses_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDivision()
    {
        return $this->hasOne(Division::className(), ['id' => 'division_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTeacher()
    {
        return $this->hasOne(User::className(), ['id' => 'teacher_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getHomeWorks()
    {
        return $this->hasMany(HomeWork::className(), ['courses_division_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuizzes()
    {
        return $this->hasMany(Quiz::className(), ['courses_division_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentCoursesDivisions()
    {
        return $this->hasMany(StudentCoursesDivision::className(), ['courses_division_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return CoursesDivisionQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new CoursesDivisionQuery(get_called_class());
    }
}
