<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "general_user_questionnaire_answers".
 *
 * @property int $id
 * @property int $general_questionnaire_id
 * @property int $general_questionnaire_answers_id
 * @property int $user_id
 * @property string $questionnaire_answers
 * @property int $created_at
 * @property int $updated_at
 *
 * @property GeneralQuestionnaire $generalQuestionnaire
 * @property GeneralQuestionnaireAnswers $generalQuestionnaireAnswers
 * @property User $user
 */
class GeneralUserQuestionnaireAnswers extends \yii\db\ActiveRecord
{
    public function beforeValidate()
    { $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        $this->created_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'general_user_questionnaire_answers';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['general_questionnaire_id', 'user_id', 'created_at'], 'required'],
            [['general_questionnaire_id', 'general_questionnaire_answers_id', 'user_id', 'created_at', 'updated_at'], 'integer'],
            [['questionnaire_answers'], 'string'],
            [['general_questionnaire_id'], 'exist', 'skipOnError' => true, 'targetClass' => GeneralQuestionnaire::className(), 'targetAttribute' => ['general_questionnaire_id' => 'id']],
            [['general_questionnaire_answers_id'], 'exist', 'skipOnError' => true, 'targetClass' => GeneralQuestionnaireAnswers::className(), 'targetAttribute' => ['general_questionnaire_answers_id' => 'id']],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'general_questionnaire_id' => Yii::t('app', 'General Questionnaire ID'),
            'general_questionnaire_answers_id' => Yii::t('app', 'General Questionnaire Answers ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'questionnaire_answers' => Yii::t('app', 'Questionnaire Answers'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGeneralQuestionnaire()
    {
        return $this->hasOne(GeneralQuestionnaire::className(), ['id' => 'general_questionnaire_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGeneralQuestionnaireAnswers()
    {
        return $this->hasOne(GeneralQuestionnaireAnswers::className(), ['id' => 'general_questionnaire_answers_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @inheritdoc
     * @return GeneralUserQuestionnaireAnswersQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new GeneralUserQuestionnaireAnswersQuery(get_called_class());
    }
}
