<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "home_work".
 *
 * @property int $id
 * @property int $courses_division_id
 * @property string $title
 * @property string $description
 * @property int $created_at
 * @property int $updated_at
 *
 * @property CoursesDivision $coursesDivision
 */
class HomeWork extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'home_work';
    }
    public function beforeValidate()
    { $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        $this->created_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['courses_division_id', 'title', 'description', 'created_at'], 'required'],
            [['courses_division_id', 'created_at', 'updated_at'], 'integer'],
            [['title', 'description'], 'string'],
            [['courses_division_id'], 'exist', 'skipOnError' => true, 'targetClass' => CoursesDivision::className(), 'targetAttribute' => ['courses_division_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'courses_division_id' => Yii::t('app', 'Courses Division ID'),
            'title' => Yii::t('app', 'Title'),
            'description' => Yii::t('app', 'Description'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCoursesDivision()
    {
        return $this->hasOne(CoursesDivision::className(), ['id' => 'courses_division_id']);
    }

    /**
     * @inheritdoc
     * @return HomeWorkQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new HomeWorkQuery(get_called_class());
    }
}
