<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "questionnaire".
 *
 * @property int $id
 * @property string $title
 * @property string $type
 * @property int $created_at
 * @property int $updated_at
 *
 * @property QuestionnaireAnswers[] $questionnaireAnswers
 * @property StudentQuestionnaireAnswers[] $studentQuestionnaireAnswers
 */
class Questionnaire extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'questionnaire';
    }
    public function beforeValidate()
    { $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        $this->created_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'created_at','type'], 'required'],
            [['title', 'type'], 'string'],
            [['created_at', 'updated_at'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'type' => Yii::t('app', 'Type'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuestionnaireAnswers()
    {
        return $this->hasMany(QuestionnaireAnswers::className(), ['questionnaire_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentQuestionnaireAnswers()
    {
        return $this->hasMany(StudentQuestionnaireAnswers::className(), ['questionnaire_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return QuestionnaireQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new QuestionnaireQuery(get_called_class());
    }
}
