<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "questionnaire_answers".
 *
 * @property int $id
 * @property int $questionnaire_id
 * @property string $title
 * @property int $created_at
 * @property int $updated_at
 *
 * @property Questionnaire $questionnaire
 * @property StudentQuestionnaireAnswers[] $studentQuestionnaireAnswers
 */
class QuestionnaireAnswers extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'questionnaire_answers';
    }
    public function beforeValidate()
    { $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        $this->created_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['questionnaire_id', 'title', 'created_at'], 'required'],
            [['questionnaire_id', 'created_at', 'updated_at'], 'integer'],
            [['title'], 'string'],
            [['questionnaire_id'], 'exist', 'skipOnError' => true, 'targetClass' => Questionnaire::className(), 'targetAttribute' => ['questionnaire_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'questionnaire_id' => Yii::t('app', 'Questionnaire ID'),
            'title' => Yii::t('app', 'Title'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuestionnaire()
    {
        return $this->hasOne(Questionnaire::className(), ['id' => 'questionnaire_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentQuestionnaireAnswers()
    {
        return $this->hasMany(StudentQuestionnaireAnswers::className(), ['questionnaire_answers_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return QuestionnaireAnswersQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new QuestionnaireAnswersQuery(get_called_class());
    }
}
