<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "quiz_questions".
 *
 * @property int $id
 * @property int $quiz_id
 * @property string $title
 * @property int $created_at
 * @property int $mark
 * @property int $updated_at
 *
 * @property Quiz $quiz
 * @property QuizQuestionsAnswers[] $quizQuestionsAnswers
 * @property QuizStudentsAnswers[] $quizStudentsAnswers
 */
class QuizQuestions extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'quiz_questions';
    }
    public function beforeValidate()
    { $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        $this->created_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }
    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['quiz_id', 'title', 'created_at','mark'], 'required'],
            [['quiz_id', 'created_at', 'updated_at'], 'integer'],
            [['title'], 'string'],
            [['quiz_id'], 'exist', 'skipOnError' => true, 'targetClass' => Quiz::className(), 'targetAttribute' => ['quiz_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'quiz_id' => Yii::t('app', 'Quiz ID'),
            'title' => Yii::t('app', 'Title'),
            'mark' => Yii::t('app', 'mark'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuiz()
    {
        return $this->hasOne(Quiz::className(), ['id' => 'quiz_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuizQuestionsAnswers()
    {
        return $this->hasMany(QuizQuestionsAnswers::className(), ['quiz_questions_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuizStudentsAnswers()
    {
        return $this->hasMany(QuizStudentsAnswers::className(), ['quiz_questions_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return QuizQuestionsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new QuizQuestionsQuery(get_called_class());
    }
}
