<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "quiz_students_answers".
 *
 * @property int $id
 * @property int $student_courses_division_id
 * @property int $quiz_questions_id
 * @property int $quiz_questions_answers_id
 * @property int $created_at
 * @property int $updated_at
 *
 * @property StudentCoursesDivision $studentCoursesDivision
 * @property QuizQuestions $quizQuestions
 * @property QuizQuestionsAnswers $quizQuestionsAnswers
 */
class QuizStudentsAnswers extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'quiz_students_answers';
    }
    public function beforeValidate()
    { $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        $this->created_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['student_courses_division_id', 'quiz_questions_id', 'quiz_questions_answers_id', 'created_at'], 'required'],
            [['student_courses_division_id', 'quiz_questions_id', 'quiz_questions_answers_id', 'created_at', 'updated_at'], 'integer'],
            [['student_courses_division_id'], 'exist', 'skipOnError' => true, 'targetClass' => StudentCoursesDivision::className(), 'targetAttribute' => ['student_courses_division_id' => 'id']],
            [['quiz_questions_id'], 'exist', 'skipOnError' => true, 'targetClass' => QuizQuestions::className(), 'targetAttribute' => ['quiz_questions_id' => 'id']],
            [['quiz_questions_answers_id'], 'exist', 'skipOnError' => true, 'targetClass' => QuizQuestionsAnswers::className(), 'targetAttribute' => ['quiz_questions_answers_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'student_courses_division_id' => Yii::t('app', 'Student Courses Division ID'),
            'quiz_questions_id' => Yii::t('app', 'Quiz Questions ID'),
            'quiz_questions_answers_id' => Yii::t('app', 'Quiz Questions Answers ID'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentCoursesDivision()
    {
        return $this->hasOne(StudentCoursesDivision::className(), ['id' => 'student_courses_division_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuizQuestions()
    {
        return $this->hasOne(QuizQuestions::className(), ['id' => 'quiz_questions_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuizQuestionsAnswers()
    {
        return $this->hasOne(QuizQuestionsAnswers::className(), ['id' => 'quiz_questions_answers_id']);
    }

    /**
     * @inheritdoc
     * @return QuizStudentsAnswersQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new QuizStudentsAnswersQuery(get_called_class());
    }
}
