<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "quiz_questions_answers".
 *
 * @property int $id
 * @property int $quiz_questions_id
 * @property string $title
 * @property int $is_true
 * @property int $created_at
 * @property int $updated_at
 *
 * @property QuizQuestions $quizQuestions
 * @property QuizStudentsAnswers[] $quizStudentsAnswers
 */
class QuizQuestionsAnswers extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'quiz_questions_answers';
    }
    public function beforeValidate()
    { $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        $this->created_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['quiz_questions_id', 'title', 'created_at'], 'required'],
            [['quiz_questions_id', 'created_at', 'updated_at'], 'integer'],
            [['title'], 'string', 'max' => 100],
            [['is_true'], 'string', 'max' => 1],
            [['quiz_questions_id'], 'exist', 'skipOnError' => true, 'targetClass' => QuizQuestions::className(), 'targetAttribute' => ['quiz_questions_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'quiz_questions_id' => Yii::t('app', 'Quiz Questions ID'),
            'title' => Yii::t('app', 'Title'),
            'is_true' => Yii::t('app', 'Is True'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuizQuestions()
    {
        return $this->hasOne(QuizQuestions::className(), ['id' => 'quiz_questions_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuizStudentsAnswers()
    {
        return $this->hasMany(QuizStudentsAnswers::className(), ['quiz_questions_answers_id' => 'id']);
    }

    /**
     * @inheritdoc
     * @return QuizQuestionsAnswersQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new QuizQuestionsAnswersQuery(get_called_class());
    }
}
