<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "student_questionnaire_answers".
 *
 * @property int $id
 * @property int $questionnaire_id
 * @property int $questionnaire_answers_id
 * @property int $student_courses_division_id
 * @property string $questionnaire_answers
 * @property int $created_at
 * @property int $updated_at
 *
 * @property Questionnaire $questionnaire
 * @property QuestionnaireAnswers $questionnaireAnswers
 * @property StudentCoursesDivision $studentCoursesDivision
 */
class StudentQuestionnaireAnswers extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'student_questionnaire_answers';
    }
    public function beforeValidate()
    { $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        $this->created_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['questionnaire_id', 'student_courses_division_id', 'created_at'], 'required'],
            [['questionnaire_id', 'questionnaire_answers_id', 'student_courses_division_id', 'created_at', 'updated_at'], 'integer'],
            [['questionnaire_answers'], 'string'],
            [['questionnaire_id'], 'exist', 'skipOnError' => true, 'targetClass' => Questionnaire::className(), 'targetAttribute' => ['questionnaire_id' => 'id']],
            [['questionnaire_answers_id'], 'exist', 'skipOnError' => true, 'targetClass' => QuestionnaireAnswers::className(), 'targetAttribute' => ['questionnaire_answers_id' => 'id']],
            [['student_courses_division_id'], 'exist', 'skipOnError' => true, 'targetClass' => StudentCoursesDivision::className(), 'targetAttribute' => ['student_courses_division_id' => 'id']],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'questionnaire_id' => Yii::t('app', 'Questionnaire ID'),
            'questionnaire_answers_id' => Yii::t('app', 'Questionnaire Answers ID'),
            'student_courses_division_id' => Yii::t('app', 'Student Courses Division ID'),
            'questionnaire_answers' => Yii::t('app', 'Questionnaire Answers'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuestionnaire()
    {
        return $this->hasOne(Questionnaire::className(), ['id' => 'questionnaire_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getQuestionnaireAnswers()
    {
        return $this->hasOne(QuestionnaireAnswers::className(), ['id' => 'questionnaire_answers_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getStudentCoursesDivision()
    {
        return $this->hasOne(StudentCoursesDivision::className(), ['id' => 'student_courses_division_id']);
    }

    /**
     * @inheritdoc
     * @return StudentQuestionnaireAnswersQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new StudentQuestionnaireAnswersQuery(get_called_class());
    }
}
