<?php

namespace app\models;

use Yii;
use yii\behaviors\TimestampBehavior;

/**
 * This is the model class for table "student_family".
 *
 * @property int $id
 * @property int $user_id
 * @property int $family_id
 * @property int $created_at
 * @property int $updated_at
 *
 * @property User $user
 * @property User $family
 */
class StudentFamily extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'student_family';
    }
    public function beforeValidate()
    { $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        $this->created_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    public function custom_function_validation($attribute){
        if($this->$attribute==$this->family_id)
            // add custom validation
            $this->addError('family_id','Must be not equal same student id');
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['user_id', 'family_id', 'created_at'], 'required'],
            [['user_id', 'family_id', 'created_at', 'updated_at'], 'integer'],
            ['user_id','custom_function_validation'],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
            [['family_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['family_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'user_id' => Yii::t('app', 'User ID'),
            'family_id' => Yii::t('app', 'Family ID'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFamily()
    {
        return $this->hasOne(User::className(), ['id' => 'family_id']);
    }

    /**
     * @inheritdoc
     * @return StudentFamilyQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new StudentFamilyQuery(get_called_class());
    }
}
