<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "times_teacher".
 *
 * @property int $id
 * @property string $text
 * @property int $teacher_id
 * @property string $days
 * @property string $time
 * @property int $created_at
 * @property int $updated_at
 *
 * @property User $teacher
 */
class TimesTeacher extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'times_teacher';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['text', 'teacher_id', 'days', 'time', 'created_at'], 'required'],
            [['text'], 'string'],
            [['teacher_id', 'created_at', 'updated_at'], 'integer'],
            [['time'], 'safe'],
            [['days'], 'string', 'max' => 100],
            [['teacher_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['teacher_id' => 'id']],
        ];
    }

    public function beforeValidate()
    { $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        $this->created_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'text' => Yii::t('app', 'Text'),
            'teacher_id' => Yii::t('app', 'Teacher ID'),
            'days' => Yii::t('app', 'Days'),
            'time' => Yii::t('app', 'Time'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTeacher()
    {
        return $this->hasOne(User::className(), ['id' => 'teacher_id']);
    }

    /**
     * @inheritdoc
     * @return TimesTeacherQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new TimesTeacherQuery(get_called_class());
    }
}
