<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "tools".
 *
 * @property int $id
 * @property string $title
 * @property int $courses_id
 * @property int $teacher_id
 * @property int $created_at
 * @property int $updated_at
 */
class Tools extends \yii\db\ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tools';
    }
    public function beforeValidate(){
        $this->created_at = time();
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    public function beforeSave($insert)
    {

        $this->created_at = time();

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'courses_id', 'teacher_id', 'created_at'], 'required'],
            [['title'], 'string'],
            [['courses_id', 'teacher_id', 'created_at', 'updated_at'], 'integer'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'ID'),
            'title' => Yii::t('app', 'Title'),
            'courses_id' => Yii::t('app', 'Courses ID'),
            'teacher_id' => Yii::t('app', 'Teacher ID'),
            'created_at' => Yii::t('app', 'Created At'),
            'updated_at' => Yii::t('app', 'Updated At'),
        ];
    }

    /**
     * @inheritdoc
     * @return ToolsQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new ToolsQuery(get_called_class());
    }
}
